"use client";

export function AISummaryPanel({
  summaryText,
  generatedAt,
  unavailable,
}: {
  summaryText: string | null;
  generatedAt: string | null;
  unavailable?: boolean;
}) {
  if (unavailable || !summaryText) {
    return (
      <section className="mt-10 rounded-2xl border border-amber-200/80 bg-[#f5f0e8] p-6 shadow-sm">
        <h2 className="text-lg font-bold text-[#0f2940]">✨ AI Neighborhood Summary</h2>
        <p className="mt-3 text-sm leading-relaxed text-slate-700">
          Summary unavailable. Configure <code className="rounded bg-white/60 px-1 text-xs">ANTHROPIC_API_KEY</code> on the
          API to generate narrative insights from tract indicators.
        </p>
      </section>
    );
  }

  return (
    <section className="mt-10 rounded-2xl border border-amber-200/60 bg-[#f5f0e8] p-6 shadow-sm">
      <h2 className="text-lg font-bold text-[#0f2940]">✨ AI Neighborhood Summary</h2>
      <div className="mt-4 space-y-3 text-sm leading-relaxed text-slate-800">
        {summaryText.split(/\n\n+/).map((para, i) => (
          <p key={i}>{para}</p>
        ))}
      </div>
      <div className="mt-6 flex flex-wrap items-center justify-between gap-2 border-t border-amber-200/50 pt-4">
        <p className="text-xs text-slate-500">{generatedAt ? `Updated ${generatedAt}` : ""}</p>
        <span className="inline-flex items-center gap-1 rounded-full bg-white/70 px-2.5 py-1 text-[10px] font-medium text-slate-600 shadow-sm">
          <span aria-hidden>✨</span> Generated by Claude AI
        </span>
      </div>
    </section>
  );
}
