"use client";

export function AISummaryPanel({
  summaryText,
  generatedAt,
  unavailable,
}: {
  summaryText: string | null;
  generatedAt: string | null;
  unavailable?: boolean;
}) {
  if (unavailable || !summaryText) {
    return (
      <section className="mt-10 rounded-2xl border border-nh-brown/10 bg-white p-6 shadow-sm">
        <h2 className="font-display text-lg font-semibold text-nh-brown">Neighborhood narrative</h2>
        <p className="mt-3 text-sm leading-relaxed text-nh-brown-muted">
          Neighborhood narrative is not available for this tract.
        </p>
      </section>
    );
  }

  return (
    <section className="mt-10 rounded-2xl border border-nh-brown/10 bg-white p-6 shadow-sm">
      <h2 className="font-display text-lg font-semibold text-nh-brown">Neighborhood narrative</h2>
      <div className="mt-4 space-y-3 text-sm leading-relaxed text-nh-brown-muted">
        {summaryText.split(/\n\n+/).map((para, i) => (
          <p key={i}>{para}</p>
        ))}
      </div>
      <div className="mt-6 flex flex-wrap items-center justify-between gap-2 border-t border-nh-brown/10 pt-4">
        <p className="text-xs text-nh-brown-muted">{generatedAt ? `Updated ${generatedAt}` : ""}</p>
        <span className="inline-flex items-center gap-1 rounded-full bg-nh-cream px-2.5 py-1 text-[10px] font-medium text-nh-brown-muted">
          Generated by Claude AI
        </span>
      </div>
    </section>
  );
}
